### PR TITLE
Added $emitters for eventMouseover() and eventMouseout() events

### PR DESCRIPTION
**Pull request by ezracelli**
Updated documentation accordingly

### CODE REVIEW

**Comment by ezracelli** [comment]
Having them as $emitters allows you to use component methods and edit component data. For example, if I want to remember the ID of the last element that was moused over, I obviously can't use the config to say `this.lastMouseover = event.id`, but even `this.$emit()` won't work.

Per the Fullcalendar docs, within `eventClick`, `eventMouseover`, and `eventMouseout`, `this` is bound to the triggering event's `<div>` element. You already solved this problem by binding `this` (i.e. the Vue component instance) to `self` before defining the methods, so `self.$emit()` gives the expected result

**Comment by BrockReece** [comment]
You can use the `config` prop for that example though.

You can use an arrow function in your `config` object as the this uses lexical scoping and is bound to the surrounding scope (the Vue component instance)

```js
config: {
  eventMouseout() {
    // this is bound to the triggering event's <div> element.
    console.log(this)
  },
  eventMouseover: (event) => {
    // this is bound to the Vue component instance
    this.lastMouseover = event.title
  },
},
```

https://codesandbox.io/s/01zvym22n0

**Comment by ezracelli** [comment]
Ahh yes, good catch! So if you don't mind me asking, what's the advantage then of `$emit`ing any of the events or even hooks? I think this is what you were referring to in your first comment -- it seems odd that it's not all or nothing. Having them as `$emit`s is more understandable overall and imo more the Vue way, but you're right, leaving them in `config` is perhaps more sustainable

**Comment by luizguilhermefr** [comment]
There is a forecast for the next release including new events?

**Comment by BrockReece** [comment]
@ezracelli When I started this wrapper, my use case was quite simple and I only really needed to emit a small number of events, but since this wrapper has been picked up by the community we have a wider range of requirements and that's when I added the `config` prop as a more scalable way of managing the events. I didn't remove the old emitted events as I didn't want to introduce breaking changes.

I also don't want you to think the work you did in the PR would be a waste or not appreciated, so I thought I would raise this question to gain a new perspectives on this plugin's design.

@luizguilhermefr I will create a new release now.

**Comment by ezracelli** [comment]
Yes that makes a lot of sense. Thank you for explaining!

**Comment by akhoury** [comment]
is this getting merged soon?

**Pull request merged**
